# Generated by Django 2.0 on 2018-07-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0005_auto_20180708_2047'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('Nos', 'Nos'), ('Mtr', 'Mtr')], default='Nos', max_length=20)),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_centre.Iso')),
            ],
        ),
    ]
