# Generated by Django 2.0 on 2019-02-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='iso',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
