# Generated by Django 2.0 on 2018-06-21 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdata',
            name='date_completed',
        ),
        migrations.AddField(
            model_name='materialdata',
            name='date_entered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='materialdata',
            name='date_fabricated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='materialdata',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='materialdata',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
