# Generated by Django 2.0 on 2018-06-12 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20180612_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdata',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialdata',
            name='completed_joints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialdata',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdata',
            name='hydrotest_status',
            field=models.CharField(choices=[('opt1', 'Not Started'), ('opt2', 'Started'), ('opt3', 'Completed')], default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdata',
            name='ndt_status',
            field=models.CharField(choices=[('opt1', 'Not Started'), ('opt2', 'Started'), ('opt3', 'Completed')], default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdata',
            name='total_joints',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
