# Generated by Django 2.0 on 2018-06-21 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=180, null=True)),
                ('last_name', models.CharField(blank=True, max_length=180, null=True)),
                ('emplyee_no', models.CharField(blank=True, max_length=180, null=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='iso no/line no')),
                ('no_of_joints', models.IntegerField(blank=True, null=True)),
                ('inch_dia', models.IntegerField(blank=True, null=True, verbose_name='Total Inch Dia')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to=settings.AUTH_USER_MODEL)),
                ('fabrication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricator', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_keeper', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='iso',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Project'),
        ),
    ]
