# Generated by Django 2.0 on 2018-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emplyee_no',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
    ]
