# Generated by Django 2.0 on 2018-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welder',
            name='employee',
        ),
        migrations.AddField(
            model_name='welder',
            name='employee',
            field=models.ManyToManyField(to='hr.Employee'),
        ),
    ]
