# Generated by Django 2.0 on 2019-02-27 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0002_auto_20190227_1020'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent', models.BooleanField(default=False)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('employee', 'timestamp')},
        ),
    ]
