# Generated by Django 2.0 on 2018-12-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-id']},
        ),
    ]
