# Generated by Django 2.0 on 2018-06-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20180623_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welder',
            name='employee',
        ),
        migrations.AddField(
            model_name='welder',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
            preserve_default=False,
        ),
    ]
