# Generated by Django 2.0 on 2018-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20180623_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='welder',
            name='welder_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
