# Generated by Django 2.0 on 2019-02-26 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0021_auto_20190216_2309'),
        ('hr', '0003_auto_20181228_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project')),
            ],
        ),
    ]
