# Generated by Django 2.0 on 2018-06-21 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20180621_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='design',
            field=models.ManyToManyField(related_name='designer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='purchase',
            field=models.ManyToManyField(related_name='purchaser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='store',
            field=models.ManyToManyField(related_name='store_keeper', to=settings.AUTH_USER_MODEL),
        ),
    ]
