# Generated by Django 2.0 on 2018-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_welder_welder_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
    ]
