# Generated by Django 2.0 on 2019-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_dailyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='present',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
