# Generated by Django 2.0 on 2018-06-21 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0005_auto_20180621_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='design',
        ),
        migrations.AddField(
            model_name='owner',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='fabrication',
        ),
        migrations.AddField(
            model_name='owner',
            name='fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='purchase',
        ),
        migrations.AddField(
            model_name='owner',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='owner',
            name='store',
        ),
        migrations.AddField(
            model_name='owner',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_keeper', to=settings.AUTH_USER_MODEL),
        ),
    ]
