# Generated by Django 2.0 on 2019-02-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20190226_1918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
