# Generated by Django 2.0 on 2018-07-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_auto_20180705_1559'),
        ('hr', '0007_auto_20180705_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='fabricator',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='welder',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.DeleteModel(
            name='Fabricator',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Welder',
        ),
    ]
