# Generated by Django 2.0 on 2018-02-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_elbow'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdata',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
