# Generated by Django 2.0 on 2018-02-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_materialdata_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='iso no/line no')),
            ],
        ),
        migrations.DeleteModel(
            name='Elbow',
        ),
        migrations.AddField(
            model_name='materialdata',
            name='iso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculations.Iso'),
            preserve_default=False,
        ),
    ]
