# Generated by Django 2.0 on 2018-02-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0004_auto_20180209_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdata',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
