# Generated by Django 2.0 on 2018-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0005_auto_20180209_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
