# Generated by Django 2.0 on 2018-02-16 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculations', '0006_materialdata_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdata',
            name='designer',
            field=models.ManyToManyField(related_name='design_engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
