# Generated by Django 2.0 on 2018-02-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0009_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdata',
            name='designer',
        ),
        migrations.AddField(
            model_name='materialdata',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculations.Designer'),
            preserve_default=False,
        ),
    ]
