# Generated by Django 2.0 on 2018-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0011_auto_20180218_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdata',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=25),
        ),
    ]
