# Generated by Django 2.0 on 2018-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0012_materialdata_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdata',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
