# Generated by Django 2.0 on 2018-06-11 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculations', '0013_auto_20180222_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='designer',
            new_name='design',
        ),
        migrations.AddField(
            model_name='owner',
            name='fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_keeper', to=settings.AUTH_USER_MODEL),
        ),
    ]
