# Generated by Django 2.0 on 2018-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0014_auto_20180611_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdata',
            name='fabricated',
            field=models.BooleanField(default=False),
        ),
    ]
