# Generated by Django 2.0 on 2019-02-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0002_auto_20190227_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso',
            name='iso_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='iso no/line no'),
        ),
    ]
