# Generated by Django 2.0 on 2018-07-07 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_centre', '0002_auto_20180707_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
