# Generated by Django 2.0 on 2018-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0003_owner_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='material_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='unit',
            field=models.CharField(choices=[('Nos', 'Nos'), ('Mtr', 'Mtr')], default='Nos', max_length=20),
        ),
    ]
