# Generated by Django 2.0 on 2019-03-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0003_auto_20190228_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoltSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='boltsize',
            unique_together={('project', 'name')},
        ),
    ]
