# Generated by Django 2.0 on 2018-12-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0003_auto_20181214_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spool_tag', models.CharField(blank=True, max_length=120, null=True)),
                ('iso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Iso')),
            ],
        ),
        migrations.CreateModel(
            name='SpoolStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='spool',
            name='spool_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.SpoolStatus'),
        ),
    ]
