# Generated by Django 2.0 on 2018-12-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0004_auto_20181221_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='Joint Nos')),
            ],
        ),
        migrations.CreateModel(
            name='FabStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fabrication',
            name='fab_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.FabStatus'),
        ),
        migrations.AddField(
            model_name='fabrication',
            name='iso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Iso'),
        ),
    ]
