# Generated by Django 2.0 on 2018-11-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0005_auto_20180708_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='iso',
            name='fitting_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_one', to='control_centre.Fitting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iso',
            name='fitting_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_two', to='control_centre.Fitting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe_one_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipe_one', to='control_centre.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe_two_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipe_two', to='control_centre.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iso',
            name='size_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_size_one', to='control_centre.Qty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iso',
            name='size_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_size_two', to='control_centre.Qty'),
            preserve_default=False,
        ),
    ]
