# Generated by Django 2.0 on 2018-11-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0006_auto_20181102_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='pipe_one_len',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipe_one_length', to='control_centre.Qty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe_two_len',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipe_two_length', to='control_centre.Qty'),
            preserve_default=False,
        ),
    ]
