# Generated by Django 2.0 on 2018-12-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0006_auto_20181228_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabstatus',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='fitupstatus',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='weldstatus',
            options={'ordering': ['-id']},
        ),
    ]
