# Generated by Django 2.0 on 2018-11-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0007_auto_20181102_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='service',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='iso',
            name='pipe_one_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipe_one', to='control_centre.Size', verbose_name='pipe one'),
        ),
        migrations.AlterField(
            model_name='iso',
            name='pipe_two_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipe_two', to='control_centre.Size', verbose_name='pipe two'),
        ),
    ]
