# Generated by Django 2.0 on 2019-03-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0007_branchfitting_coupling_reducer_tee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spool',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='spool',
            unique_together={('iso', 'spool_tag')},
        ),
    ]
