# Generated by Django 2.0 on 2019-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0007_auto_20181228_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='spool',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
