# Generated by Django 2.0 on 2019-03-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0008_auto_20190303_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolt',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.BoltSize'),
        ),
    ]
