# Generated by Django 2.0 on 2019-01-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0008_spool_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iso',
            options={'ordering': ['service__name']},
        ),
    ]
