# Generated by Django 2.0 on 2019-03-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0009_auto_20190303_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducer',
            name='type',
            field=models.CharField(blank=True, choices=[('CONCENTRIC', 'CONCENTRIC'), ('ECCENTRIC', 'ECCENTRIC')], max_length=30, null=True),
        ),
    ]
