# Generated by Django 2.0 on 2018-11-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0009_auto_20181102_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
