# Generated by Django 2.0 on 2019-01-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0009_auto_20190113_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spoolstatus',
            options={'ordering': ['-id']},
        ),
    ]
