# Generated by Django 2.0 on 2019-01-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0010_auto_20190113_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
    ]
