# Generated by Django 2.0 on 2018-11-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0010_auto_20181102_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='total_pipe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qty',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
