# Generated by Django 2.0 on 2018-11-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0011_auto_20181109_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso',
            name='pipe_one_len',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iso',
            name='pipe_one_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iso',
            name='pipe_two_len',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iso',
            name='pipe_two_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
