# Generated by Django 2.0 on 2019-01-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0011_service_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('project', 'name')},
        ),
    ]
