# Generated by Django 2.0 on 2018-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0012_auto_20181109_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iso',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
