# Generated by Django 2.0 on 2019-01-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0012_auto_20190117_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('project', 'name')},
        ),
    ]
