# Generated by Django 2.0 on 2019-01-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0013_auto_20190117_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flangeclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lineclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='flangeclass',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AddField(
            model_name='lineclass',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='flangeclass',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lineclass',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('project', 'name')},
        ),
    ]
