# Generated by Django 2.0 on 2018-11-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0013_auto_20181109_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='pipe_one_len',
            new_name='pipe',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='pipe_one_size',
            new_name='pipe_length',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='fitting_one',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='fitting_two',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='pipe_two_len',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='pipe_two_size',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='size_one',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='size_two',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='total_pipe',
        ),
    ]
