# Generated by Django 2.0 on 2018-11-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0015_auto_20181110_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='pipe2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe_length2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
