# Generated by Django 2.0 on 2019-01-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0015_auto_20190118_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boltgrade',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fabstatus',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gasketmaterial',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='spoolstatus',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='boltgrade',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AddField(
            model_name='fabstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AddField(
            model_name='gasketmaterial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AddField(
            model_name='spoolstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='boltgrade',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='gasketmaterial',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='spoolstatus',
            unique_together={('project', 'name')},
        ),
    ]
