# Generated by Django 2.0 on 2019-01-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0016_auto_20190118_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabrication',
            name='fab_status',
        ),
        migrations.RemoveField(
            model_name='fabrication',
            name='fitup_status',
        ),
        migrations.RemoveField(
            model_name='fabrication',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='fabrication',
            name='weld_status',
        ),
        migrations.AlterModelOptions(
            name='fitupstatus',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weldstatus',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='fitupstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.AddField(
            model_name='weldstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Project'),
        ),
        migrations.DeleteModel(
            name='Fabrication',
        ),
    ]
