# Generated by Django 2.0 on 2018-11-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0016_auto_20181111_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='iso',
            name='pipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Pipe'),
        ),
    ]
