# Generated by Django 2.0 on 2018-11-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0017_auto_20181116_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iso',
            name='pipe',
        ),
        migrations.AddField(
            model_name='pipe',
            name='iso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Iso'),
        ),
    ]
