# Generated by Django 2.0 on 2018-11-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0018_auto_20181116_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iso',
            name='inch_dia',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='no_of_joints',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='pipe2',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='pipe_length',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='pipe_length2',
        ),
    ]
