# Generated by Django 2.0 on 2019-02-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0019_erectionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitupstatus',
            name='project',
        ),
        migrations.RemoveField(
            model_name='weldstatus',
            name='project',
        ),
    ]
