# Generated by Django 2.0 on 2018-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0019_auto_20181116_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso',
            name='pipe1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe_1l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='pipe_2l',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
