# Generated by Django 2.0 on 2019-02-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0020_auto_20190216_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erectionstatus',
            name='project',
        ),
        migrations.RemoveField(
            model_name='fabstatus',
            name='project',
        ),
        migrations.DeleteModel(
            name='ErectionStatus',
        ),
        migrations.DeleteModel(
            name='FabStatus',
        ),
    ]
