# Generated by Django 2.0 on 2019-01-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0007_auto_20181228_2003'),
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndt', models.CharField(choices=[('Not Started', 'Not Started'), ('Going on', 'Going on'), ('Completed', 'Completed')], default='Not Started', max_length=40, verbose_name='NDT Status')),
                ('hydro', models.CharField(choices=[('Not Started', 'Not Started'), ('Going on', 'Going on'), ('Completed', 'Completed')], default='Not Started', max_length=40, verbose_name='Hydrotest Status')),
                ('radio', models.CharField(choices=[('Not Started', 'Not Started'), ('Going on', 'Going on'), ('Completed', 'Completed')], default='Not Started', max_length=40, verbose_name='Radiography Status')),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=40, verbose_name='Joint Status')),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_centre.Iso')),
            ],
        ),
        migrations.RemoveField(
            model_name='joint',
            name='hydro',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='ndt',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='qc_checked',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='radio',
        ),
        migrations.AddField(
            model_name='qc',
            name='joint_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Joint'),
        ),
    ]
