# Generated by Django 2.0 on 2019-02-27 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0002_auto_20190227_1020'),
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdtStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitup_inspection_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('welding_inspection_date', models.DateField(blank=True, null=True)),
                ('hydro_test_inspection_date', models.DateField(blank=True, null=True)),
                ('radiography_inspection_date', models.DateField(blank=True, null=True)),
                ('fitup_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitup_status', to='construction.NdtStatus')),
                ('hydro_test_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hydro_status', to='construction.NdtStatus')),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_centre.Iso')),
            ],
            options={
                'ordering': ['-fitup_inspection_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='joint',
            options={'ordering': ['-date_completed']},
        ),
        migrations.AddField(
            model_name='joint',
            name='fitup_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.FitUpStatus'),
        ),
        migrations.AddField(
            model_name='joint',
            name='fitup_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time taken for Fit-Up'),
        ),
        migrations.AddField(
            model_name='joint',
            name='iso_comleted',
            field=models.BooleanField(default=False, verbose_name='Is Mechanical Job Completed for this ISO'),
        ),
        migrations.AddField(
            model_name='joint',
            name='weld_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Welding Date'),
        ),
        migrations.AddField(
            model_name='joint',
            name='weld_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.WeldStatus'),
        ),
        migrations.AddField(
            model_name='joint',
            name='welding_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time taken for Welding'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fit-Up Date'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='sch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Schedule'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Size'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='welder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welder', to='hr.Employee'),
        ),
        migrations.RemoveField(
            model_name='joint',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='hydro',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='ndt',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='qc_checked',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='joint',
            unique_together={('iso', 'joint_no')},
        ),
        migrations.AddField(
            model_name='qc',
            name='joint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.Joint'),
        ),
        migrations.AddField(
            model_name='qc',
            name='radiography_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_status', to='construction.NdtStatus'),
        ),
        migrations.AddField(
            model_name='qc',
            name='welding_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welding_status', to='construction.NdtStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='qc',
            unique_together={('iso', 'joint')},
        ),
    ]
