# Generated by Django 2.0 on 2018-07-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=40, verbose_name='Joint Status'),
        ),
    ]
