# Generated by Django 2.0 on 2018-06-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joint',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='fabricator',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='joint',
            name='welder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Employee'),
            preserve_default=False,
        ),
    ]
