# Generated by Django 2.0 on 2018-07-03 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_joint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint',
            name='qc_checked',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
