# Generated by Django 2.0 on 2018-07-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_auto_20180719_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
