# Generated by Django 2.0 on 2019-01-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_auto_20190101_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qc',
            old_name='joint_no',
            new_name='joint',
        ),
    ]
