# Generated by Django 2.0 on 2018-06-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20180621_1723'),
        ('construction', '0002_auto_20180621_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint',
            name='engineer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Engineer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joint',
            name='fabricator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Fabricator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joint',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Supervisor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joint',
            name='welder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Welder'),
        ),
    ]
