# Generated by Django 2.0 on 2018-07-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_joint_qc_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to='hr.Employee'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='fabricator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricator', to='hr.Employee'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='hr.Employee'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='welder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welder', to='hr.Employee'),
        ),
    ]
