# Generated by Django 2.0 on 2019-01-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_auto_20190101_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qc',
            options={'ordering': ['-id']},
        ),
    ]
