# Generated by Django 2.0 on 2019-01-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_auto_20190111_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='sch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Schedule'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.Size'),
        ),
    ]
