# Generated by Django 2.0 on 2018-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_auto_20180705_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='qc_checked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
