# Generated by Django 2.0 on 2019-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_auto_20190307_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='sr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stress Relief'),
        ),
    ]
