# Generated by Django 2.0 on 2019-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_qc_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='fn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FN'),
        ),
        migrations.AlterField(
            model_name='qc',
            name='hydro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HYDRO'),
        ),
        migrations.AlterField(
            model_name='qc',
            name='pmi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PMI'),
        ),
        migrations.AlterField(
            model_name='qc',
            name='pneum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PNEUM'),
        ),
        migrations.AlterField(
            model_name='qc',
            name='rt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RT'),
        ),
    ]
