# Generated by Django 2.0 on 2019-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_auto_20190118_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint',
            name='iso_comleted',
            field=models.BooleanField(default=False, verbose_name='Is Mechanical Job Completed for Iso'),
        ),
    ]
