# Generated by Django 2.0 on 2019-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_joint_iso_comleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='iso_comleted',
            field=models.BooleanField(default=False, verbose_name='Is Mechanical Job Completed for this ISO'),
        ),
    ]
