# Generated by Django 2.0 on 2019-02-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_auto_20190208_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='erection_status',
            field=models.CharField(blank=True, choices=[('erected', 'Erected'), ('pending', 'Pending')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='status',
            field=models.CharField(choices=[('erected', 'Erected'), ('pending', 'Pending')], default='Pending', max_length=40, verbose_name='Joint Status'),
        ),
    ]
