# Generated by Django 2.0 on 2019-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_auto_20190209_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='erection_status',
            field=models.CharField(blank=True, choices=[('erected', 'erected'), ('pending', 'pending')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='status',
            field=models.CharField(choices=[('erected', 'erected'), ('pending', 'pending')], default='Pending', max_length=40, verbose_name='Joint Status'),
        ),
    ]
