# Generated by Django 2.0 on 2019-02-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_auto_20190215_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='erection_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_centre.ErectionStatus'),
        ),
    ]
