# Generated by Django 2.0 on 2019-02-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0013_auto_20190215_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joint',
            name='erection_status',
        ),
    ]
