# Generated by Django 2.0 on 2019-02-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0014_remove_joint_erection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdtStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='qc',
            options={'ordering': ['-fitup_inspection_date']},
        ),
        migrations.RenameField(
            model_name='qc',
            old_name='timestamp',
            new_name='fitup_inspection_date',
        ),
        migrations.RemoveField(
            model_name='qc',
            name='hydro',
        ),
        migrations.RemoveField(
            model_name='qc',
            name='ndt',
        ),
        migrations.RemoveField(
            model_name='qc',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='qc',
            name='status',
        ),
        migrations.AddField(
            model_name='qc',
            name='hydrotest_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qc',
            name='radiography_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qc',
            name='welding_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qc',
            name='fitup_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitup_status', to='construction.NdtStatus'),
        ),
        migrations.AddField(
            model_name='qc',
            name='hydro_test_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hydro_status', to='construction.NdtStatus'),
        ),
        migrations.AddField(
            model_name='qc',
            name='radiography_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_status', to='construction.NdtStatus'),
        ),
        migrations.AddField(
            model_name='qc',
            name='welding_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welding_status', to='construction.NdtStatus'),
        ),
    ]
