# Generated by Django 2.0 on 2019-02-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0015_auto_20190216_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qc',
            old_name='hydrotest_inspection_date',
            new_name='hydro_test_inspection_date',
        ),
    ]
