# Generated by Django 2.0 on 2019-02-22 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0016_auto_20190216_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='radiography_inspection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
