# Generated by Django 2.0 on 2019-02-22 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0017_auto_20190222_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='fitup_inspection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='hydro_test_inspection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='welding_inspection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
