# Generated by Django 2.0 on 2019-02-25 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_centre', '0021_auto_20190216_2309'),
        ('construction', '0018_auto_20190222_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='qc',
            name='hydro_test_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='radiography_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qc',
            name='welding_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='joint',
            unique_together={('iso', 'joint_no')},
        ),
        migrations.AlterUniqueTogether(
            name='qc',
            unique_together={('iso', 'joint')},
        ),
    ]
