# Generated by Django 2.0 on 2019-02-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0019_auto_20190225_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc',
            name='fitup_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fitup_status', to='construction.NdtStatus'),
        ),
    ]
