# Generated by Django 2.0 on 2019-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0020_auto_20190225_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joint',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='joint',
            name='fitup_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time taken for Fit-Up'),
        ),
        migrations.AddField(
            model_name='joint',
            name='welding_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time taken for Welding'),
        ),
    ]
