# Generated by Django 2.0 on 2019-02-25 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0022_auto_20190226_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint',
            name='weld_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Welding Date'),
        ),
        migrations.AlterField(
            model_name='joint',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fit-Up Date'),
        ),
    ]
